local_costmap:
   global_frame: /odom
   robot_base_frame: /base_footprint
   update_frequency: 5.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 30.0
   height: 30.0
   resolution: 0.05
   transform_tolerance: 3.0
   map_type: costmap
   observation_sources: scan
   scan: {data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true, expected_update_rate: 0.3,inf_is_valid: true}
